services:
  ai-dialogue-service:
    build: ./services/ai-dialogue-service
    container_name: ai-dialogue-service
    environment:
      - INTERNAL_API_KEY=aZk928j7i6429P
      - AI_INFERENCE_SERVICE_URL=http://ai-inference-service:8080/v1/chat/completions
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=Chatapult
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
  
  ai-dialogue-service-ingest:
    build: ./services/ai-dialogue-service
    container_name: ai-dialogue-service-ingest
    command: python ingest.py
    environment:
      - INTERNAL_API_KEY=aZk928j7i6429P
      - AI_INFERENCE_SERVICE_URL=http://ai-inference-service:8080/v1/chat/completions
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=Chatapult
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
    depends_on:
      - qdrant
    restart: "no"

  ai-inference-service:
    build: ./services/ai-inference-service
    container_name: ai-inference-service
    environment:
      - INTERNAL_API_KEY=aZk928j7i6429P
      - OPENAI_API_KEY=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
    ports:
      - "8080:8080"

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb+srv://2200530:Q52kQspUKhL8S3XV@chatapult.tjn3e.mongodb.net/Chatapult?retryWrites=true&w=majority&appName=Chatapult
      - JWT_SECRET=8baa27b1ed70ddd4b5b4f5f582791c7a6fce2b19a35e7f3d4a5bc2ed6069ad65
    ports:
      - "4000:4000"

  database-service:
    build: ./services/database-service
    container_name: database-service
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://2200530:Q52kQspUKhL8S3XV@chatapult.tjn3e.mongodb.net/Chatapult?retryWrites=true&w=majority&appName=Chatapult
    ports:
      - "5000:5000"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./services/ai-dialogue-service/qdrant_storage:/qdrant/storage

  frontend:
    build: ./services/frontend
    container_name: frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_AUTH_SERVICE_URL=http://auth-service:4000
      - NEXT_PUBLIC_DATABASE_SERVICE_URL=http://database-service:5000
      - NEXT_PUBLIC_AI_DIALOGUE_SERVICE_URL=http://ai-dialogue-service:8000
      - NEXT_PUBLIC_AI_DIALOGUE_SERVICE_API_KEY=aZk928j7i6429P
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - database-service
      - ai-dialogue-service
